<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
    'key' => 'group_581b97aebc0aa',
    'title' => '[Page] Page Blog',
    'fields' => array (
        array (
            'key' => 'field_581badc120ab4',
            'label' => 'General',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array (
            'key' => 'field_5902ff0db0fca',
            'label' => 'Output of content',
            'name' => 'output_content',
            'type' => 'select',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array (
                'top' => 'Top',
                'bottom' => 'Bottom',
            ),
            'default_value' => array (
                0 => 'top',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        array (
            'key' => 'field_5884e941ab1a0',
            'label' => 'Variants styles',
            'name' => 'blog_variants_styles',
            'type' => 'select',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array (
                'classic' => 'Classic',
                'minimal' => 'Minimal',
                'creative' => 'Creative',
            ),
            'default_value' => array (
                0 => 'classic',
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
        ),
        array (
            'key' => 'field_581b97ce49551',
            'label' => 'Quantity displayed posts',
            'name' => 'blog_max_posts',
            'type' => 'number',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_581b981349552',
                        'operator' => '==',
                        'value' => 'classic',
                    ),
                ),
                array (
                    array (
                        'field' => 'field_581b981349552',
                        'operator' => '==',
                        'value' => 'ajax-loader',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 5,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
        array (
            'key' => 'field_58825e6917909',
            'label' => 'Animation',
            'name' => 'blog_animation',
            'type' => 'select',
            'value' => NULL,
            'instructions' => 'preview https://daneden.github.io/animate.css/',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array (
                'none' => 'None',
                'wow bounce' => 'Bounce',
                'wow flash' => 'Flash',
                'wow pulse' => 'Pulse',
                'wow rubberBand' => 'RubberBand',
                'wow shake' => 'Shake',
                'wow swing' => 'Swing',
                'wow tada' => 'Tada',
                'wow wobble' => 'Wobble',
                'wow jello' => 'Jello',
                'wow bounceIn' => 'BounceIn',
                'wow bounceInDown' => 'BounceInDown',
                'wow bounceInLeft' => 'BounceInLeft',
                'wow bounceInRight' => 'BounceInRight',
                'wow bounceInUp' => 'BounceInUp',
                'wow bounceOut' => 'BounceOut',
                'wow bounceOutDown' => 'BounceOutDown',
                'wow bounceOutLeft' => 'BounceOutLeft',
                'wow bounceOutRight' => 'BounceOutRight',
                'wow bounceOutUp' => 'BounceOutUp',
                'wow fadeIn' => 'FadeIn',
                'wow fadeInDown' => 'FadeInDown',
                'wow fadeInDownBig' => 'FadeInDownBig',
                'wow fadeInLeft' => 'FadeInLeft',
                'wow fadeInLeftBig' => 'FadeInLeftBig',
                'wow fadeInRight' => 'FadeInRight',
                'wow fadeInRightBig' => 'FadeInRightBig',
                'wow fadeInUp' => 'FadeInUp',
                'wow fadeInUpBig' => 'FadeInUpBig',
                'wow fadeOut' => 'FadeOut',
                'wow fadeOutDown' => 'FadeOutDown',
                'wow fadeOutDownBig' => 'FadeOutDownBig',
                'wow fadeOutLeft' => 'FadeOutLeft',
                'wow fadeOutLeftBig' => 'FadeOutLeftBig',
                'wow fadeOutRight' => 'FadeOutRight',
                'wow fadeOutRightBig' => 'FadeOutRightBig',
                'wow fadeOutUp' => 'FadeOutUp',
                'wow fadeOutUpBig' => 'FadeOutUpBig',
                'wow flip' => 'Flip',
                'wow flipInX' => 'FlipInX',
                'wow flipInY' => 'FlipInY',
                'wow flipOutX' => 'FlipOutX',
                'wow flipOutY' => 'FlipOutY',
                'wow lightSpeedIn' => 'LightSpeedIn',
                'wow lightSpeedOut' => 'LightSpeedOut',
                'wow rotateIn' => 'RotateIn',
                'wow rotateInDownLeft' => 'RotateInDownLeft',
                'wow rotateInDownRight' => 'RotateInDownRight',
                'wow rotateInUpLeft' => 'RotateInUpLeft',
                'wow rotateInUpRight' => 'RotateInUpRight',
                'wow rotateOut' => 'RotateOut',
                'wow rotateOutDownLeft' => 'RotateOutDownLeft',
                'wow rotateOutDownRight' => 'RotateOutDownRight',
                'wow rotateOutUpLeft' => 'RotateOutUpLeft',
                'wow rotateOutUpRight' => 'RotateOutUpRight',
                'wow slideInUp' => 'SlideInUp',
                'wow slideInDown' => 'SlideInDown',
                'wow slideInLeft' => 'SlideInLeft',
                'wow slideInRight' => 'SlideInRight',
                'wow slideOutUp' => 'SlideOutUp',
                'wow slideOutDown' => 'SlideOutDown',
                'wow slideOutLeft' => 'SlideOutLeft',
                'wow slideOutRight' => 'SlideOutRight',
                'wow zoomIn' => 'ZoomIn',
                'wow zoomInDown' => 'ZoomInDown',
                'wow zoomInLeft' => 'ZoomInLeft',
                'wow zoomInRight' => 'ZoomInRight',
                'wow zoomInUp' => 'ZoomInUp',
                'wow zoomOut' => 'ZoomOut',
                'wow zoomOutDown' => 'ZoomOutDown',
                'wow zoomOutLeft' => 'ZoomOutLeft',
                'wow zoomOutRight' => 'ZoomOutRight',
                'wow zoomOutUp' => 'ZoomOutUp',
                'wow hinge' => 'Hinge',
                'wow rollIn' => 'RollIn',
                'wow rollOut' => 'RollOut',
            ),
            'default_value' => array (
                0 => 'none',
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
        ),
        array (
            'key' => 'field_587bc6462e77f',
            'label' => 'Column',
            'name' => 'blog_column',
            'type' => 'select',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array (
                'blog-column-one' => '1',
                'blog-column-two' => '2',
                'blog-column-three' => '3',
            ),
            'default_value' => array (
                0 => 'blog-column-one',
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
        ),
        array (
            'key' => 'field_581b981349552',
            'label' => 'Pagination',
            'name' => 'pagination',
            'type' => 'select',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array (
                'classic' => 'Classic',
                'ajax-loader' => 'Ajax',
                'hide' => 'Hide',
            ),
            'default_value' => array (
                0 => 'classic',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'template-blog.php',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_581b9604d61e8',
    'title' => '[Page] Page Custom',
    'fields' => array (
        array (
            'key' => 'field_581b960d667c6',
            'label' => 'General',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array (
            'key' => 'field_586b9847fe77a',
            'label' => 'Parallax',
            'name' => 'parallax_header',
            'type' => 'select',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array (
                'show' => 'Show',
                'hide' => 'Hide',
            ),
            'default_value' => array (
                0 => 'show',
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
        ),
        array (
            'key' => 'field_5884e481d2361',
            'label' => 'Text Animation',
            'name' => 'text_animation_parallax',
            'type' => 'select',
            'value' => NULL,
            'instructions' => 'preview https://daneden.github.io/animate.css/',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_586b9847fe77a',
                        'operator' => '==',
                        'value' => 'show',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array (
                'none' => 'None',
                'wow bounce' => 'Bounce',
                'wow flash' => 'Flash',
                'wow pulse' => 'Pulse',
                'wow rubberBand' => 'RubberBand',
                'wow shake' => 'Shake',
                'wow swing' => 'Swing',
                'wow tada' => 'Tada',
                'wow wobble' => 'Wobble',
                'wow jello' => 'Jello',
                'wow bounceIn' => 'BounceIn',
                'wow bounceInDown' => 'BounceInDown',
                'wow bounceInLeft' => 'BounceInLeft',
                'wow bounceInRight' => 'BounceInRight',
                'wow bounceInUp' => 'BounceInUp',
                'wow bounceOut' => 'BounceOut',
                'wow bounceOutDown' => 'BounceOutDown',
                'wow bounceOutLeft' => 'BounceOutLeft',
                'wow bounceOutRight' => 'BounceOutRight',
                'wow bounceOutUp' => 'BounceOutUp',
                'wow fadeIn' => 'FadeIn',
                'wow fadeInDown' => 'FadeInDown',
                'wow fadeInDownBig' => 'FadeInDownBig',
                'wow fadeInLeft' => 'FadeInLeft',
                'wow fadeInLeftBig' => 'FadeInLeftBig',
                'wow fadeInRight' => 'FadeInRight',
                'wow fadeInRightBig' => 'FadeInRightBig',
                'wow fadeInUp' => 'FadeInUp',
                'wow fadeInUpBig' => 'FadeInUpBig',
                'wow fadeOut' => 'FadeOut',
                'wow fadeOutDown' => 'FadeOutDown',
                'wow fadeOutDownBig' => 'FadeOutDownBig',
                'wow fadeOutLeft' => 'FadeOutLeft',
                'wow fadeOutLeftBig' => 'FadeOutLeftBig',
                'wow fadeOutRight' => 'FadeOutRight',
                'wow fadeOutRightBig' => 'FadeOutRightBig',
                'wow fadeOutUp' => 'FadeOutUp',
                'wow fadeOutUpBig' => 'FadeOutUpBig',
                'wow flip' => 'Flip',
                'wow flipInX' => 'FlipInX',
                'wow flipInY' => 'FlipInY',
                'wow flipOutX' => 'FlipOutX',
                'wow flipOutY' => 'FlipOutY',
                'wow lightSpeedIn' => 'LightSpeedIn',
                'wow lightSpeedOut' => 'LightSpeedOut',
                'wow rotateIn' => 'RotateIn',
                'wow rotateInDownLeft' => 'RotateInDownLeft',
                'wow rotateInDownRight' => 'RotateInDownRight',
                'wow rotateInUpLeft' => 'RotateInUpLeft',
                'wow rotateInUpRight' => 'RotateInUpRight',
                'wow rotateOut' => 'RotateOut',
                'wow rotateOutDownLeft' => 'RotateOutDownLeft',
                'wow rotateOutDownRight' => 'RotateOutDownRight',
                'wow rotateOutUpLeft' => 'RotateOutUpLeft',
                'wow rotateOutUpRight' => 'RotateOutUpRight',
                'wow slideInUp' => 'SlideInUp',
                'wow slideInDown' => 'SlideInDown',
                'wow slideInLeft' => 'SlideInLeft',
                'wow slideInRight' => 'SlideInRight',
                'wow slideOutUp' => 'SlideOutUp',
                'wow slideOutDown' => 'SlideOutDown',
                'wow slideOutLeft' => 'SlideOutLeft',
                'wow slideOutRight' => 'SlideOutRight',
                'wow zoomIn' => 'ZoomIn',
                'wow zoomInDown' => 'ZoomInDown',
                'wow zoomInLeft' => 'ZoomInLeft',
                'wow zoomInRight' => 'ZoomInRight',
                'wow zoomInUp' => 'ZoomInUp',
                'wow zoomOut' => 'ZoomOut',
                'wow zoomOutDown' => 'ZoomOutDown',
                'wow zoomOutLeft' => 'ZoomOutLeft',
                'wow zoomOutRight' => 'ZoomOutRight',
                'wow zoomOutUp' => 'ZoomOutUp',
                'wow hinge' => 'Hinge',
                'wow rollIn' => 'RollIn',
                'wow rollOut' => 'RollOut',
            ),
            'default_value' => array (
                0 => 'none',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        array (
            'key' => 'field_587162a7edc9f',
            'label' => 'Title',
            'name' => 'title_parallax',
            'type' => 'text',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array (
            'key' => 'field_59ccb69a3c50a',
            'label' => 'Background Video',
            'name' => 'background_video_parallax',
            'type' => 'select',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_586b9847fe77a',
                        'operator' => '==',
                        'value' => 'show',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array (
                'none' => 'None',
                'youtube' => 'YouTube',
                'vimeo' => 'Vimeo',
                'html5' => 'HTML5',
            ),
            'default_value' => array (
                0 => 'none',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        array (
            'key' => 'field_59ccb6e23c50b',
            'label' => 'YouTube',
            'name' => 'youtube_parallax',
            'type' => 'url',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_586b9847fe77a',
                        'operator' => '==',
                        'value' => 'show',
                    ),
                    array (
                        'field' => 'field_59ccb69a3c50a',
                        'operator' => '==',
                        'value' => 'youtube',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'https://www.youtube.com/watch?v=ab0TSkLe-E0',
            'placeholder' => '',
        ),
        array (
            'key' => 'field_59ccb86a3c50d',
            'label' => 'Vimeo',
            'name' => 'vimeo_parallax',
            'type' => 'url',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_586b9847fe77a',
                        'operator' => '==',
                        'value' => 'show',
                    ),
                    array (
                        'field' => 'field_59ccb69a3c50a',
                        'operator' => '==',
                        'value' => 'vimeo',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'https://vimeo.com/110138539',
            'placeholder' => '',
        ),
        array (
            'key' => 'field_59ccb89d3c50f',
            'label' => 'Self Hosted',
            'name' => 'self_hosted_parallax',
            'type' => 'file',
            'value' => NULL,
            'instructions' => 'mp4, webm',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_586b9847fe77a',
                        'operator' => '==',
                        'value' => 'show',
                    ),
                    array (
                        'field' => 'field_59ccb69a3c50a',
                        'operator' => '==',
                        'value' => 'html5',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => 'mp4, webm',
        ),
        array (
            'key' => 'field_586c081227b12',
            'label' => 'Container',
            'name' => 'container',
            'type' => 'select',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array (
                'full' => 'Full',
                'box' => 'Box',
            ),
            'default_value' => array (
                0 => 'box',
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
        ),
        array (
            'key' => 'field_581b9747f8044',
            'label' => 'Sidebar',
            'name' => 'sidebar',
            'type' => 'select',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array (
                'show' => 'Show',
                'hide' => 'Hide',
            ),
            'default_value' => array (
                0 => 'show',
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
        ),
        array (
            'key' => 'field_58acba50c1cd0',
            'label' => 'Position Sidebar',
            'name' => 'position_sidebar',
            'type' => 'select',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_581b9747f8044',
                        'operator' => '==',
                        'value' => 'show',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array (
                'left-sidebar' => 'Left',
                'right-sidebar' => 'Right',
            ),
            'default_value' => array (
                0 => 'right-sidebar',
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'template-page.php',
            ),
        ),
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'template-blog.php',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_58c7e4273dacd',
    'title' => '[Post Format] Audio',
    'fields' => array (
        array (
            'key' => 'field_58c7e42755d8b',
            'label' => 'Audio Host Type',
            'name' => 'audio_host_type',
            'type' => 'radio',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array (
                'embed-code' => 'Embed Code',
                'self-hosted' => 'Self Hosted',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => 'embed-code',
            'layout' => 'vertical',
            'return_format' => 'value',
        ),
        array (
            'key' => 'field_58c7e42756173',
            'label' => 'Audio Embed Code',
            'name' => 'audio_embed_code',
            'type' => 'oembed',
            'value' => NULL,
            'instructions' => 'Paste the link audio here. If you want to use self hosted, you may leave it blank and choose self hosted option above.',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_58c7e42755d8b',
                        'operator' => '==',
                        'value' => 'embed-code',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'width' => '',
            'height' => '',
        ),
        array (
            'key' => 'field_58c7e4275655b',
            'label' => 'Self Hosted',
            'name' => 'audio_self_hosted',
            'type' => 'file',
            'value' => NULL,
            'instructions' => 'Upload or select your self hosted Audio. If you want to use embed code. you may leave it blank and choose embed code option above.',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_58c7e42755d8b',
                        'operator' => '==',
                        'value' => 'self-hosted',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => 'mp3, ogg, wma, m4a, wav',
        ),
        array (
            'key' => 'field_58c92cafbabc9',
            'label' => 'Title',
            'name' => 'audio_self_hosted_title',
            'type' => 'text',
            'value' => NULL,
            'instructions' => 'Title audio',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_58c7e42755d8b',
                        'operator' => '==',
                        'value' => 'self-hosted',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_format',
                'operator' => '==',
                'value' => 'audio',
            ),
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_58c6d552c3391',
    'title' => '[Post Format] Gallery',
    'fields' => array (
        array (
            'key' => 'field_58c6e52eea17d',
            'label' => 'Gallery Type',
            'name' => 'gallery_type',
            'type' => 'radio',
            'value' => NULL,
            'instructions' => 'Choose the Gallery type you wnt to display',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array (
                'slider' => 'Slider Gallery',
                'tiled' => 'Tiled Gallery',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'vertical',
            'return_format' => 'value',
        ),
        array (
            'key' => 'field_58c6f0b5ea17e',
            'label' => 'Upload or Choose Images',
            'name' => 'type_gallery_images',
            'type' => 'gallery',
            'value' => NULL,
            'instructions' => 'Choose or upload images for this gallery',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'min' => '',
            'max' => '',
            'insert' => 'append',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_format',
                'operator' => '==',
                'value' => 'gallery',
            ),
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_58c7cdc28caf6',
    'title' => '[Post Format] Link',
    'fields' => array (
        array (
            'key' => 'field_58c7cde415e47',
            'label' => 'URL',
            'name' => 'link_format_post_options',
            'type' => 'url',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_format',
                'operator' => '==',
                'value' => 'link',
            ),
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_58c7cfaf85e5a',
    'title' => '[Post Format] Quote',
    'fields' => array (
        array (
            'key' => 'field_58c7cfc84e1f9',
            'label' => 'Quote Content',
            'name' => 'quote_content',
            'type' => 'textarea',
            'value' => NULL,
            'instructions' => 'Please type the text of your quote here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'br',
        ),
        array (
            'key' => 'field_58c7cfdd4e1fa',
            'label' => 'Quote Source Name',
            'name' => 'quote_source_name',
            'type' => 'text',
            'value' => NULL,
            'instructions' => 'Type the author name / name of the quote source.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_58c7cffc4e1fb',
            'label' => 'Quote Source Link (URL)',
            'name' => 'quote_source_link_url',
            'type' => 'url',
            'value' => NULL,
            'instructions' => 'Paste the link of the quote source. The author name will be linked to this link.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_format',
                'operator' => '==',
                'value' => 'quote',
            ),
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_58c7d17ada313',
    'title' => '[Post Format] Status',
    'fields' => array (
        array (
            'key' => 'field_58c7d1894a1cc',
            'label' => 'Status Type',
            'name' => 'status_type',
            'type' => 'radio',
            'value' => NULL,
            'instructions' => 'Choose the status type you wnt to post',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array (
                'twitter' => 'Twitter Status',
                'facebook' => 'Facebook Status',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'vertical',
            'return_format' => 'value',
        ),
        array (
            'key' => 'field_58c7d1c04a1cd',
            'label' => 'Status link (URL)',
            'name' => 'status_link_url',
            'type' => 'url',
            'value' => NULL,
            'instructions' => 'Paste the Link of the status',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_format',
                'operator' => '==',
                'value' => 'status',
            ),
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_58c7d24e31831',
    'title' => '[Post Format] Video',
    'fields' => array (
        array (
            'key' => 'field_58c7d267e49ff',
            'label' => 'Video Host Type',
            'name' => 'video_host_type',
            'type' => 'radio',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array (
                'embed-code' => 'Embed Code',
                'self-hosted' => 'Self Hosted',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => 'embed-code',
            'layout' => 'vertical',
            'return_format' => 'value',
        ),
        array (
            'key' => 'field_58c7d2a4e4a00',
            'label' => 'Video Embed Code',
            'name' => 'video_embed_code',
            'type' => 'oembed',
            'value' => NULL,
            'instructions' => 'Paste the link video here. If you want to use self hosted, you may leave it blank and choose self hosted option above.',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_58c7d267e49ff',
                        'operator' => '==',
                        'value' => 'embed-code',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'width' => '',
            'height' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_format',
                'operator' => '==',
                'value' => 'video',
            ),
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array (
    'key' => 'group_581b98b1a9361',
    'title' => '[Post] Portfolio Item',
    'fields' => array (
        array (
            'key' => 'field_588929aad5a1f',
            'label' => 'Gallery projects',
            'name' => 'gallery_projects',
            'type' => 'gallery',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'library' => 'all',
            'min' => '',
            'max' => '',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'insert' => 'append',
        ),
        array (
            'key' => 'field_59d62ee5ba388',
            'label' => 'Parallax',
            'name' => 'parallax_header',
            'type' => 'select',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array (
                'show' => 'Show',
                'hide' => 'Hide',
            ),
            'default_value' => array (
                0 => 'hide',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        array (
            'key' => 'field_59d62f20ba389',
            'label' => 'Text Animation',
            'name' => 'text_animation_parallax',
            'type' => 'select',
            'value' => NULL,
            'instructions' => 'preview https://daneden.github.io/animate.css/',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_59d62ee5ba388',
                        'operator' => '==',
                        'value' => 'show',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array (
                'none' => 'None',
                'wow bounce' => 'Bounce',
                'wow flash' => 'Flash',
                'wow pulse' => 'Pulse',
                'wow rubberBand' => 'RubberBand',
                'wow shake' => 'Shake',
                'wow swing' => 'Swing',
                'wow tada' => 'Tada',
                'wow wobble' => 'Wobble',
                'wow jello' => 'Jello',
                'wow bounceIn' => 'BounceIn',
                'wow bounceInDown' => 'BounceInDown',
                'wow bounceInLeft' => 'BounceInLeft',
                'wow bounceInRight' => 'BounceInRight',
                'wow bounceInUp' => 'BounceInUp',
                'wow bounceOut' => 'BounceOut',
                'wow bounceOutDown' => 'BounceOutDown',
                'wow bounceOutLeft' => 'BounceOutLeft',
                'wow bounceOutRight' => 'BounceOutRight',
                'wow bounceOutUp' => 'BounceOutUp',
                'wow fadeIn' => 'FadeIn',
                'wow fadeInDown' => 'FadeInDown',
                'wow fadeInDownBig' => 'FadeInDownBig',
                'wow fadeInLeft' => 'FadeInLeft',
                'wow fadeInLeftBig' => 'FadeInLeftBig',
                'wow fadeInRight' => 'FadeInRight',
                'wow fadeInRightBig' => 'FadeInRightBig',
                'wow fadeInUp' => 'FadeInUp',
                'wow fadeInUpBig' => 'FadeInUpBig',
                'wow fadeOut' => 'FadeOut',
                'wow fadeOutDown' => 'FadeOutDown',
                'wow fadeOutDownBig' => 'FadeOutDownBig',
                'wow fadeOutLeft' => 'FadeOutLeft',
                'wow fadeOutLeftBig' => 'FadeOutLeftBig',
                'wow fadeOutRight' => 'FadeOutRight',
                'wow fadeOutRightBig' => 'FadeOutRightBig',
                'wow fadeOutUp' => 'FadeOutUp',
                'wow fadeOutUpBig' => 'FadeOutUpBig',
                'wow flip' => 'Flip',
                'wow flipInX' => 'FlipInX',
                'wow flipInY' => 'FlipInY',
                'wow flipOutX' => 'FlipOutX',
                'wow flipOutY' => 'FlipOutY',
                'wow lightSpeedIn' => 'LightSpeedIn',
                'wow lightSpeedOut' => 'LightSpeedOut',
                'wow rotateIn' => 'RotateIn',
                'wow rotateInDownLeft' => 'RotateInDownLeft',
                'wow rotateInDownRight' => 'RotateInDownRight',
                'wow rotateInUpLeft' => 'RotateInUpLeft',
                'wow rotateInUpRight' => 'RotateInUpRight',
                'wow rotateOut' => 'RotateOut',
                'wow rotateOutDownLeft' => 'RotateOutDownLeft',
                'wow rotateOutDownRight' => 'RotateOutDownRight',
                'wow rotateOutUpLeft' => 'RotateOutUpLeft',
                'wow rotateOutUpRight' => 'RotateOutUpRight',
                'wow slideInUp' => 'SlideInUp',
                'wow slideInDown' => 'SlideInDown',
                'wow slideInLeft' => 'SlideInLeft',
                'wow slideInRight' => 'SlideInRight',
                'wow slideOutUp' => 'SlideOutUp',
                'wow slideOutDown' => 'SlideOutDown',
                'wow slideOutLeft' => 'SlideOutLeft',
                'wow slideOutRight' => 'SlideOutRight',
                'wow zoomIn' => 'ZoomIn',
                'wow zoomInDown' => 'ZoomInDown',
                'wow zoomInLeft' => 'ZoomInLeft',
                'wow zoomInRight' => 'ZoomInRight',
                'wow zoomInUp' => 'ZoomInUp',
                'wow zoomOut' => 'ZoomOut',
                'wow zoomOutDown' => 'ZoomOutDown',
                'wow zoomOutLeft' => 'ZoomOutLeft',
                'wow zoomOutRight' => 'ZoomOutRight',
                'wow zoomOutUp' => 'ZoomOutUp',
                'wow hinge' => 'Hinge',
                'wow rollIn' => 'RollIn',
                'wow rollOut' => 'RollOut',
            ),
            'default_value' => array (
                0 => 'none',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        array (
            'key' => 'field_59d62f64ba38a',
            'label' => 'Title',
            'name' => 'title_parallax',
            'type' => 'text',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array (
            'key' => 'field_59d6327c91a84',
            'label' => 'Image',
            'name' => 'parallax_image',
            'type' => 'image',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_59d62ee5ba388',
                        'operator' => '==',
                        'value' => 'show',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array (
            'key' => 'field_59d62fffba38b',
            'label' => 'Background Video',
            'name' => 'background_video_parallax',
            'type' => 'select',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_59d62ee5ba388',
                        'operator' => '==',
                        'value' => 'show',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array (
                'none' => 'None',
                'youtube' => 'YouTube',
                'vimeo' => 'Vimeo',
                'html5' => 'HTML5',
            ),
            'default_value' => array (
                0 => 'none',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        array (
            'key' => 'field_59d63036ba38c',
            'label' => 'YouTube',
            'name' => 'youtube_parallax',
            'type' => 'url',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_59d62ee5ba388',
                        'operator' => '==',
                        'value' => 'show',
                    ),
                    array (
                        'field' => 'field_59d62fffba38b',
                        'operator' => '==',
                        'value' => 'youtube',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'https://www.youtube.com/watch?v=ab0TSkLe-E0',
            'placeholder' => '',
        ),
        array (
            'key' => 'field_59d63060ba38e',
            'label' => 'Vimeo',
            'name' => 'vimeo_parallax',
            'type' => 'url',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_59d62ee5ba388',
                        'operator' => '==',
                        'value' => 'show',
                    ),
                    array (
                        'field' => 'field_59d62fffba38b',
                        'operator' => '==',
                        'value' => 'vimeo',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'https://vimeo.com/110138539',
            'placeholder' => '',
        ),
        array (
            'key' => 'field_59d630d3ba390',
            'label' => 'Self Hosted',
            'name' => 'self_hosted_parallax',
            'type' => 'file',
            'value' => NULL,
            'instructions' => 'mp4',
            'required' => 0,
            'conditional_logic' => array (
                array (
                    array (
                        'field' => 'field_59d62ee5ba388',
                        'operator' => '==',
                        'value' => 'show',
                    ),
                    array (
                        'field' => 'field_59d62fffba38b',
                        'operator' => '==',
                        'value' => 'html5',
                    ),
                ),
            ),
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => 'mp4',
        ),
        array (
            'key' => 'field_5889e8561fd5a',
            'label' => 'Project Description',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array (
            'key' => 'field_5889ea017abcf',
            'label' => 'Visible',
            'name' => 'visible_details',
            'type' => 'select',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array (
                'show' => 'Show',
                'hide' => 'Hide',
            ),
            'default_value' => array (
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
        ),
        array (
            'key' => 'field_5889ea777abd0',
            'label' => 'Project details',
            'name' => 'project_details',
            'type' => 'text',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Project details',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array (
            'key' => 'field_5889f95f2c74a',
            'label' => 'Title #1',
            'name' => 'author_title',
            'type' => 'text',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Author',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5889f9f02c74b',
            'label' => 'Author',
            'name' => 'author',
            'type' => 'text',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'John Smith',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5889ea947abd1',
            'label' => 'Title #2',
            'name' => 'client_name_title',
            'type' => 'text',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Client',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5889f72dd0b3f',
            'label' => 'Client name',
            'name' => 'client_name',
            'type' => 'text',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Elon Musk',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5889eaad7abd2',
            'label' => 'Title #3',
            'name' => 'project_date_title',
            'type' => 'text',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Project date',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array (
            'key' => 'field_5889f77cd0b40',
            'label' => 'Project date',
            'name' => 'project_date',
            'type' => 'text',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '31 December 2017',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array (
            'key' => 'field_5889eac27abd3',
            'label' => 'Title #4',
            'name' => 'project_location_title',
            'type' => 'text',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Project location',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array (
            'key' => 'field_5889f795d0b41',
            'label' => 'Project location',
            'name' => 'project_location',
            'type' => 'text',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'California, USA',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_59d5e91aed353',
            'label' => 'Social icons',
            'name' => 'social_icons_portfolio',
            'type' => 'select',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array (
                'show' => 'Show',
                'hide' => 'Hide',
            ),
            'default_value' => array (
                0 => 'show',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'portfolio',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

endif;